import { useState } from 'react';
import { ArrowRight, CheckCircle2, Globe2, LockKeyhole, Radar, ShieldCheck, TriangleAlert } from 'lucide-react';

const demo = { domain:'yourbusiness.co.za', score:72, grade:'Good', summary:{passed:7,warnings:3,failed:2}, checks:[{category:'Email protection',name:'DMARC policy',status:'fail',message:'Add a DMARC record to stop criminals impersonating your email.'},{category:'Website security',name:'Security headers',status:'warning',message:'Add browser security headers to reduce common website attacks.'},{category:'Website security',name:'HTTPS & certificate',status:'pass',message:'Your website connection is encrypted.'}] };
const API = import.meta.env.VITE_API_URL || '';
function Status({status}) { return status==='pass'?<CheckCircle2 className="text-emerald-600"/>:<TriangleAlert className={status==='fail'?'text-red-500':'text-amber-500'}/> }
export default function App(){ const [domain,setDomain]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function scan(e){e.preventDefault(); setLoading(true);setError('');try{const r=await fetch(`${API}/api/scan/domain`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain})});if(!r.ok)throw new Error('Scan could not be completed');setResult(await r.json())}catch{setError('We could not reach the scanner. Showing an example report instead.');setResult(demo)}finally{setLoading(false)}}
 if(result) return <Dashboard result={result} onBack={()=>setResult(null)}/>;
 return <main><section className="grid-bg min-h-[78vh] bg-ink text-white"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><div className="flex items-center gap-2 text-lg font-bold"><ShieldCheck className="text-lime"/> GuardLayer <span className="text-lime">Pulse</span></div><span className="rounded-full border border-white/15 px-3 py-1 text-xs text-white/70">Built for South African SMEs</span></nav><div className="mx-auto max-w-4xl px-6 py-24 text-center"><div className="mx-auto mb-6 w-fit rounded-full border border-lime/30 bg-lime/10 px-4 py-2 text-sm text-lime">Know your cyber risk in minutes</div><h1 className="text-5xl font-bold tracking-tight md:text-7xl">Is your business<br/><span className="text-lime">ready for an attack?</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg text-slate-300">Get a practical security health check for your website and email setup. No jargon, no intrusive testing, just clear priorities.</p><form onSubmit={scan} className="mx-auto mt-10 flex max-w-2xl flex-col gap-3 rounded-2xl bg-white p-3 shadow-2xl sm:flex-row"><div className="flex flex-1 items-center gap-3 px-3"><Globe2 className="text-slate-400"/><input required value={domain} onChange={e=>setDomain(e.target.value)} className="w-full py-3 text-ink outline-none" placeholder="yourbusiness.co.za"/></div><button className="flex items-center justify-center gap-2 rounded-xl bg-lime px-6 py-4 font-bold text-ink hover:bg-white" disabled={loading}>{loading?'Scanning…':'Check my risk'} <ArrowRight size={18}/></button></form>{error&&<p className="mt-4 text-sm text-amber-300">{error}</p>}<p className="mt-4 text-xs text-slate-500">Safe, read-only checks • No dark web scraping • Results kept private</p></div></section><section className="mx-auto grid max-w-6xl gap-6 px-6 py-16 md:grid-cols-3">{[[Radar,'See the gaps','We check the public security signals attackers notice first.'],[LockKeyhole,'Understand the risk','A simple score turns technical findings into business impact.'],[CheckCircle2,'Fix what matters','Get a plain-English checklist, ordered by priority.']].map(([I,t,d])=><article className="rounded-2xl border border-slate-200 bg-white p-7" key={t}><I className="mb-5 text-emerald-600"/><h2 className="font-bold">{t}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></article>)}</section></main> }
function Dashboard({result,onBack}){const checks=result.checks||[];return <main className="min-h-screen bg-[#f4f7f3]"><nav className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><div className="flex items-center gap-2 font-bold"><ShieldCheck className="text-emerald-600"/> GuardLayer Pulse</div><button onClick={onBack} className="text-sm font-semibold">Scan another domain</button></div></nav><div className="mx-auto max-w-6xl px-6 py-10"><p className="text-sm text-slate-500">Security report for</p><h1 className="text-3xl font-bold">{result.domain}</h1><div className="mt-8 grid gap-6 md:grid-cols-[1fr_2fr]"><section className="rounded-3xl bg-ink p-8 text-white"><p className="text-sm text-slate-400">Cyber Risk Score</p><div className="my-6 text-8xl font-bold text-lime">{result.score}</div><p className="text-xl font-semibold">{result.grade||'Needs attention'}</p><p className="mt-3 text-sm leading-6 text-slate-400">Higher is safer. Improve the priority items to strengthen your business.</p></section><section className="rounded-3xl border bg-white p-8"><h2 className="text-xl font-bold">Your fix checklist</h2><p className="mt-2 text-sm text-slate-500">Start at the top — these actions have the biggest impact.</p><div className="mt-6 space-y-3">{checks.map((c,i)=><div key={`${c.name}-${i}`} className="flex gap-4 rounded-2xl border border-slate-100 bg-slate-50 p-4"><Status status={c.status}/><div><div className="flex flex-wrap gap-2"><h3 className="font-semibold">{c.name}</h3><span className="rounded-full bg-white px-2 py-1 text-[10px] uppercase text-slate-500">{c.category}</span></div><p className="mt-1 text-sm text-slate-600">{c.message}</p></div></div>)}</div></section></div></div></main>}
