import { useState } from 'react';
import { ArrowRight, CheckCircle2, Globe2, LockKeyhole, Radar, ShieldCheck, TriangleAlert } from 'lucide-react';
import { mainRiskSummary, normalizeFindings } from './findings.js';

const demo = { domain:'yourbusiness.co.za', score:72, grade:'Good', main_risk_summary:'Your biggest risk is email impersonation because DMARC is missing and DKIM could not be confirmed.', checks:[{category:'Email protection',title:'DMARC policy',status:'fail',severity:'high',plainEnglishSummary:'DMARC is missing, leaving your email domain open to impersonation.',whyItMatters:'DMARC tells mail systems how to handle forged messages.',recommendedFix:'Ask your email provider to publish DMARC with p=reject.',evidence:null},{category:'Website security',title:'HTTPS connection',status:'pass',severity:'low',plainEnglishSummary:'The website uses an encrypted HTTPS connection.',whyItMatters:'HTTPS protects customer data in transit.',recommendedFix:'No action needed.',evidence:{connected:true}}] };
const API = import.meta.env.VITE_API_URL || '';
function Status({status}) { return status==='pass'?<CheckCircle2 className="text-emerald-600"/>:<TriangleAlert className={status==='fail'?'text-red-500':'text-amber-500'}/> }
export default function App(){ const [domain,setDomain]=useState(''); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 async function scan(e){e.preventDefault(); setLoading(true);setError('');try{const r=await fetch(`${API}/api/scan/domain`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({domain})});if(!r.ok)throw new Error('Scan could not be completed');setResult(await r.json())}catch{setError('We could not reach the scanner. Showing an example report instead.');setResult(demo)}finally{setLoading(false)}}
 if(result) return <Dashboard result={result} onBack={()=>setResult(null)}/>;
 return <main><section className="grid-bg min-h-[78vh] bg-ink text-white"><nav className="mx-auto flex max-w-6xl items-center justify-between px-6 py-6"><div className="flex items-center gap-2 text-lg font-bold"><ShieldCheck className="text-lime"/> GuardLayer <span className="text-lime">Pulse</span></div><span className="rounded-full border border-white/15 px-3 py-1 text-xs text-white/70">Built for South African SMEs</span></nav><div className="mx-auto max-w-4xl px-6 py-24 text-center"><div className="mx-auto mb-6 w-fit rounded-full border border-lime/30 bg-lime/10 px-4 py-2 text-sm text-lime">Know your cyber risk in minutes</div><h1 className="text-5xl font-bold tracking-tight md:text-7xl">Is your business<br/><span className="text-lime">ready for an attack?</span></h1><p className="mx-auto mt-6 max-w-2xl text-lg text-slate-300">Get a practical security health check for your website and email setup. No jargon, no intrusive testing, just clear priorities.</p><form onSubmit={scan} className="mx-auto mt-10 flex max-w-2xl flex-col gap-3 rounded-2xl bg-white p-3 shadow-2xl sm:flex-row"><div className="flex flex-1 items-center gap-3 px-3"><Globe2 className="text-slate-400"/><input required value={domain} onChange={e=>setDomain(e.target.value)} className="w-full py-3 text-ink outline-none" placeholder="yourbusiness.co.za"/></div><button className="flex items-center justify-center gap-2 rounded-xl bg-lime px-6 py-4 font-bold text-ink hover:bg-white" disabled={loading}>{loading?'Scanning…':'Check my risk'} <ArrowRight size={18}/></button></form>{error&&<p className="mt-4 text-sm text-amber-300">{error}</p>}<p className="mt-4 text-xs text-slate-500">Safe, read-only checks • No dark web scraping • Results kept private</p></div></section><section className="mx-auto grid max-w-6xl gap-6 px-6 py-16 md:grid-cols-3">{[[Radar,'See the gaps','We check the public security signals attackers notice first.'],[LockKeyhole,'Understand the risk','A simple score turns technical findings into business impact.'],[CheckCircle2,'Fix what matters','Get a plain-English checklist, ordered by priority.']].map(([I,t,d])=><article className="rounded-2xl border border-slate-200 bg-white p-7" key={t}><I className="mb-5 text-emerald-600"/><h2 className="font-bold">{t}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></article>)}</section></main> }
function Badge({children}){return <span className="rounded-full bg-slate-100 px-2 py-1 text-[10px] font-bold uppercase text-slate-600">{children}</span>}
function CheckCard({c,technical=false}){return <div className="flex gap-4 rounded-2xl border border-slate-200 bg-white p-4"><Status status={c.status}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{c.title}</h3><Badge>{c.category}</Badge><Badge>{c.status.replace('_',' ')}</Badge><Badge>{c.severity}</Badge></div><p className="mt-2 text-sm font-medium text-slate-700">{c.plainEnglishSummary}</p><div className="mt-3 grid gap-3 text-xs text-slate-600 md:grid-cols-2"><p><b>Why it matters:</b> {c.whyItMatters}</p><p><b>Recommended action:</b> {c.recommendedAction}</p></div><details className="mt-3 text-xs text-slate-500" open={false}><summary className="cursor-pointer font-semibold">{technical?'Raw evidence':'View evidence'}</summary><ul className="mt-2 space-y-1 rounded-lg bg-slate-50 p-3">{c.evidence.map((item,i)=><li className="break-words font-mono" key={i}>{item}</li>)}</ul></details></div></div>}
function Dashboard({result,onBack}){const checks=normalizeFindings(result.checks||[]);const fixes=checks.filter(c=>['fail','warning','needs_review'].includes(c.status));const passed=checks.filter(c=>c.status==='pass');return <main className="min-h-screen bg-[#f4f7f3]"><nav className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-5"><div className="flex items-center gap-2 font-bold"><ShieldCheck className="text-emerald-600"/> GuardLayer Pulse</div><button onClick={onBack} className="text-sm font-semibold">Scan another domain</button></div></nav><div className="mx-auto max-w-6xl space-y-6 px-6 py-10"><div><p className="text-sm text-slate-500">Security report for</p><h1 className="text-3xl font-bold">{result.domain}</h1></div><div className="grid gap-6 md:grid-cols-[1fr_2fr]"><section className="rounded-3xl bg-ink p-8 text-white"><p className="text-sm text-slate-400">Cyber Risk Score</p><div className="my-6 text-8xl font-bold text-lime">{result.score}</div><p className="text-xl font-semibold">{result.grade||'Needs attention'}</p></section><section className="rounded-3xl border bg-white p-8"><h2 className="text-xl font-bold">Main Risk Summary</h2><p className="mt-4 text-lg leading-8 text-slate-700">{mainRiskSummary(checks)}</p></section></div><Report title="Priority Fixes" description="Items that failed, look weak, or need a person to confirm them." checks={fixes} empty="No priority fixes were found."/><Report title="Passed Checks" description="These protections were confirmed during the scan." checks={passed} empty="No passed checks were recorded."/><Report title="Technical Details" description="All scan results and raw evidence for your IT or website provider." checks={checks} technical empty="No findings were recorded."/></div></main>}
function Report({title,description,checks,empty,technical=false}){return <section className="rounded-3xl border bg-white p-8"><h2 className="text-xl font-bold">{title}</h2><p className="mt-2 text-sm text-slate-500">{description}</p><div className="mt-6 space-y-3">{checks.length?checks.map(c=><CheckCard c={c} technical={technical} key={c.id}/>):<p className="text-sm text-slate-500">{empty}</p>}</div></section>}
